name: Plugin Request
description: Request a 3rd party library support
title: "[Plugin request]: "
labels: ["plugin"]
assignees: 
  - PaulleDemon
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request for new plugin


  - type: input
    id: plugin
    attributes:
      label: Name of the plugin
      placeholder: plugin name
    validations:
        required: true

  - type: input
    id: plugin-link
    attributes:
      label: Link to plugin
      placeholder: plugin link
    validations:
        required: true