name: Plugin Request
description: Request support for a third-party library
title: "[Plugin Request]: "
labels: ["plugin"]
assignees:
  - PaulleDemon
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new plugin.

  - type: input
    id: plugin
    attributes:
      label: Name of the plugin
      placeholder: Enter the plugin name
    validations:
      required: true

  - type: input
    id: plugin-link
    attributes:
      label: Link to the plugin
      placeholder: Enter the plugin link
    validations:
      required: true
